language: generic
sudo: require
services:
  - docker

before_install:
  - docker build -t mathiase/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mathiase/docker-react npm run test